# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OBS(object):
    def setupUi(self, OBS):
        OBS.setObjectName("OBS")
        OBS.resize(1136, 834)
        font = QtGui.QFont()
        font.setPointSize(10)
        OBS.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Images/Ekran Görüntüleri/Ekran görüntüsü 2025-06-06 000601.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OBS.setWindowIcon(icon)
        self.stackedWidget = QtWidgets.QStackedWidget(OBS)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -20, 1141, 861))
        self.stackedWidget.setStyleSheet("#sfgiris{\n"
"background-color: #d6eaff;\n"
"}\n"
"#sfkayit{\n"
"background-color: #d6eaff;\n"
"}\n"
"#sfana{\n"
"    background-color: white;\n"
"}\n"
"#sfbilgi{\n"
"    background-color: white;}\n"
"#sfnot{\n"
"    background-color: white;\n"
"}\n"
"#sfsinif{\n"
"background-color: white;\n"
"}\n"
"#sfogretmen{\n"
"background-color: white;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.sfgiris = QtWidgets.QWidget()
        self.sfgiris.setObjectName("sfgiris")
        self.gbgiris = QtWidgets.QGroupBox(self.sfgiris)
        self.gbgiris.setGeometry(QtCore.QRect(250, 180, 691, 441))
        self.gbgiris.setStyleSheet("#gbgiris{\n"
"    background-color: white;\n"
"    border: 2px solid #333;\n"
"    border-radius: 15px;\n"
"    padding: 20px;\n"
"}")
        self.gbgiris.setTitle("")
        self.gbgiris.setObjectName("gbgiris")
        self.lngirisid = QtWidgets.QLineEdit(self.gbgiris)
        self.lngirisid.setGeometry(QtCore.QRect(200, 200, 301, 31))
        self.lngirisid.setToolTip("")
        self.lngirisid.setStyleSheet("#lngirisid{\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lngirisid.setText("")
        self.lngirisid.setMaxLength(3)
        self.lngirisid.setClearButtonEnabled(True)
        self.lngirisid.setObjectName("lngirisid")
        self.lngirissifre = QtWidgets.QLineEdit(self.gbgiris)
        self.lngirissifre.setGeometry(QtCore.QRect(200, 260, 301, 31))
        self.lngirissifre.setStyleSheet("#lngirissifre{ \n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lngirissifre.setMaxLength(30)
        self.lngirissifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lngirissifre.setClearButtonEnabled(True)
        self.lngirissifre.setObjectName("lngirissifre")
        self.label = QtWidgets.QLabel(self.gbgiris)
        self.label.setGeometry(QtCore.QRect(70, 80, 581, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.gbgiris)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(260, 310, 160, 100))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btngiris = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btngiris.setStyleSheet("#btngiris{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btngiris:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btngiris.setObjectName("btngiris")
        self.verticalLayout_3.addWidget(self.btngiris)
        self.btngiriskayit = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btngiriskayit.setStyleSheet("#btngiriskayit{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btngiriskayit:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btngiriskayit.setObjectName("btngiriskayit")
        self.verticalLayout_3.addWidget(self.btngiriskayit)
        self.btngiriscikis = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.btngiriscikis.setStyleSheet("#btngiriscikis{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btngiriscikis:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btngiriscikis.setObjectName("btngiriscikis")
        self.verticalLayout_3.addWidget(self.btngiriscikis)
        self.stackedWidget.addWidget(self.sfgiris)
        self.sfkayit = QtWidgets.QWidget()
        self.sfkayit.setStyleSheet("")
        self.sfkayit.setObjectName("sfkayit")
        self.gbkayit = QtWidgets.QGroupBox(self.sfkayit)
        self.gbkayit.setGeometry(QtCore.QRect(240, 200, 691, 441))
        self.gbkayit.setStyleSheet("#gbkayit{\n"
"    background-color: white;\n"
"    border: 2px solid #333;\n"
"    border-radius: 15px;\n"
"    padding: 20px;\n"
"}")
        self.gbkayit.setTitle("")
        self.gbkayit.setObjectName("gbkayit")
        self.lnkayitid = QtWidgets.QLineEdit(self.gbkayit)
        self.lnkayitid.setGeometry(QtCore.QRect(200, 20, 301, 31))
        self.lnkayitid.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lnkayitid.setToolTip("")
        self.lnkayitid.setStyleSheet("#lnkayitid{\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lnkayitid.setText("")
        self.lnkayitid.setMaxLength(3)
        self.lnkayitid.setClearButtonEnabled(True)
        self.lnkayitid.setObjectName("lnkayitid")
        self.lnkayitad = QtWidgets.QLineEdit(self.gbkayit)
        self.lnkayitad.setGeometry(QtCore.QRect(200, 70, 301, 31))
        self.lnkayitad.setStyleSheet("#lnkayitad{\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lnkayitad.setMaxLength(30)
        self.lnkayitad.setClearButtonEnabled(True)
        self.lnkayitad.setObjectName("lnkayitad")
        self.lnkayitsoyad = QtWidgets.QLineEdit(self.gbkayit)
        self.lnkayitsoyad.setGeometry(QtCore.QRect(200, 120, 301, 31))
        self.lnkayitsoyad.setStyleSheet("#lnkayitsoyad{\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lnkayitsoyad.setMaxLength(30)
        self.lnkayitsoyad.setClearButtonEnabled(True)
        self.lnkayitsoyad.setObjectName("lnkayitsoyad")
        self.lnkayitsifretekrar = QtWidgets.QLineEdit(self.gbkayit)
        self.lnkayitsifretekrar.setGeometry(QtCore.QRect(200, 280, 301, 31))
        self.lnkayitsifretekrar.setStyleSheet("#lnkayitsifretekrar{\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lnkayitsifretekrar.setMaxLength(30)
        self.lnkayitsifretekrar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnkayitsifretekrar.setClearButtonEnabled(True)
        self.lnkayitsifretekrar.setObjectName("lnkayitsifretekrar")
        self.lnkayitsifre = QtWidgets.QLineEdit(self.gbkayit)
        self.lnkayitsifre.setGeometry(QtCore.QRect(200, 240, 301, 31))
        self.lnkayitsifre.setStyleSheet("#lnkayitsifre{\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f9f9f9;\n"
"}")
        self.lnkayitsifre.setMaxLength(30)
        self.lnkayitsifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnkayitsifre.setClearButtonEnabled(True)
        self.lnkayitsifre.setObjectName("lnkayitsifre")
        self.cbbolum = QtWidgets.QComboBox(self.gbkayit)
        self.cbbolum.setGeometry(QtCore.QRect(200, 170, 301, 31))
        self.cbbolum.setObjectName("cbbolum")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.gbkayit)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(260, 330, 160, 100))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnkayit = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btnkayit.setStyleSheet("#btnkayit{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btnkayit:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btnkayit.setObjectName("btnkayit")
        self.verticalLayout_6.addWidget(self.btnkayit)
        self.btngirisdon = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btngirisdon.setStyleSheet("#btngirisdon{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btngirisdon:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btngirisdon.setObjectName("btngirisdon")
        self.verticalLayout_6.addWidget(self.btngirisdon)
        self.btnkayitcikis = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.btnkayitcikis.setStyleSheet("#btnkayitcikis{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btnkayitcikis:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btnkayitcikis.setObjectName("btnkayitcikis")
        self.verticalLayout_6.addWidget(self.btnkayitcikis)
        self.lbsifre = QtWidgets.QLabel(self.gbkayit)
        self.lbsifre.setGeometry(QtCore.QRect(200, 210, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbsifre.setFont(font)
        self.lbsifre.setStyleSheet("color: red;")
        self.lbsifre.setText("")
        self.lbsifre.setObjectName("lbsifre")
        self.stackedWidget.addWidget(self.sfkayit)
        self.sfana = QtWidgets.QWidget()
        self.sfana.setObjectName("sfana")
        self.frame = QtWidgets.QFrame(self.sfana)
        self.frame.setGeometry(QtCore.QRect(-1, 19, 331, 841))
        self.frame.setStyleSheet("#frame{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 301, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnkapa = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnkapa.setFont(font)
        self.btnkapa.setStyleSheet("#btnkapa {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#btnkapa:hover {\n"
"    background-color: darkred;\n"
"}\n"
"\n"
"#btnkapa:pressed {\n"
"    background-color: #990000;\n"
"}")
        self.btnkapa.setObjectName("btnkapa")
        self.verticalLayout.addWidget(self.btnkapa)
        self.btncikis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btncikis.setStyleSheet("\n"
"#btncikis {\n"
"    background-color: #2ecc71;   \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"#btncikis:hover {\n"
"    background-color: #27ae60;  \n"
"}\n"
"#btncikis:pressed{\n"
"background-color: #1e8449;\n"
"}\n"
"")
        self.btncikis.setObjectName("btncikis")
        self.verticalLayout.addWidget(self.btncikis)
        self.btnana = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnana.setFont(font)
        self.btnana.setStyleSheet("#btnana {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnana:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnana.setObjectName("btnana")
        self.verticalLayout.addWidget(self.btnana)
        self.btnobilgi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnobilgi.setFont(font)
        self.btnobilgi.setStyleSheet("#btnobilgi {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnobilgi:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnobilgi.setObjectName("btnobilgi")
        self.verticalLayout.addWidget(self.btnobilgi)
        self.btnnotbilgi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnnotbilgi.setFont(font)
        self.btnnotbilgi.setStyleSheet("#btnnotbilgi {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnnotbilgi:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnnotbilgi.setObjectName("btnnotbilgi")
        self.verticalLayout.addWidget(self.btnnotbilgi)
        self.btnsinif = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnsinif.setFont(font)
        self.btnsinif.setStyleSheet("#btnsinif {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnsinif:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnsinif.setObjectName("btnsinif")
        self.verticalLayout.addWidget(self.btnsinif)
        self.frame_2 = QtWidgets.QFrame(self.sfana)
        self.frame_2.setGeometry(QtCore.QRect(330, 10, 801, 80))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbbilgi = QtWidgets.QLabel(self.frame_2)
        self.lbbilgi.setGeometry(QtCore.QRect(150, 30, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbbilgi.setFont(font)
        self.lbbilgi.setText("")
        self.lbbilgi.setAlignment(QtCore.Qt.AlignCenter)
        self.lbbilgi.setObjectName("lbbilgi")
        self.gbana = QtWidgets.QGroupBox(self.sfana)
        self.gbana.setGeometry(QtCore.QRect(350, 100, 761, 731))
        self.gbana.setStyleSheet("#gbana{\n"
"  background-color: white;\n"
"    border: 2px solid #333;\n"
"    border-radius: 15px;\n"
"    padding: 20px;\n"
"}")
        self.gbana.setTitle("")
        self.gbana.setObjectName("gbana")
        self.label_2 = QtWidgets.QLabel(self.gbana)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 571, 291))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.sfana)
        self.sfbilgi = QtWidgets.QWidget()
        self.sfbilgi.setObjectName("sfbilgi")
        self.frame_3 = QtWidgets.QFrame(self.sfbilgi)
        self.frame_3.setGeometry(QtCore.QRect(0, 20, 331, 841))
        self.frame_3.setStyleSheet("#frame_3{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 301, 721))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnkapa2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnkapa2.setFont(font)
        self.btnkapa2.setStyleSheet("#btnkapa2{\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#btnkapa2:hover {\n"
"    background-color: darkred;\n"
"}\n"
"\n"
"#btnkapa2:pressed {\n"
"    background-color: #990000;\n"
"}")
        self.btnkapa2.setObjectName("btnkapa2")
        self.verticalLayout_2.addWidget(self.btnkapa2)
        self.btncikis2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btncikis2.setStyleSheet("\n"
"#btncikis2 {\n"
"    background-color: #2ecc71;   \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"#btncikis2:hover {\n"
"    background-color: #27ae60;  \n"
"}\n"
"#btncikis2:pressed{\n"
"background-color: #1e8449;\n"
"}\n"
"")
        self.btncikis2.setObjectName("btncikis2")
        self.verticalLayout_2.addWidget(self.btncikis2)
        self.btnana2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnana2.setFont(font)
        self.btnana2.setStyleSheet("#btnana2 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnana2:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnana2.setObjectName("btnana2")
        self.verticalLayout_2.addWidget(self.btnana2)
        self.btnobilgi2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnobilgi2.setFont(font)
        self.btnobilgi2.setStyleSheet("#btnobilgi2 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnobilgi2:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnobilgi2.setObjectName("btnobilgi2")
        self.verticalLayout_2.addWidget(self.btnobilgi2)
        self.btnnotbilgi2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnnotbilgi2.setFont(font)
        self.btnnotbilgi2.setStyleSheet("#btnnotbilgi2 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnnotbilgi2:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnnotbilgi2.setObjectName("btnnotbilgi2")
        self.verticalLayout_2.addWidget(self.btnnotbilgi2)
        self.btnsinif2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnsinif2.setFont(font)
        self.btnsinif2.setStyleSheet("#btnsinif2 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnsinif2:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnsinif2.setObjectName("btnsinif2")
        self.verticalLayout_2.addWidget(self.btnsinif2)
        self.frame_4 = QtWidgets.QFrame(self.sfbilgi)
        self.frame_4.setGeometry(QtCore.QRect(330, 10, 801, 80))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbbilgi2 = QtWidgets.QLabel(self.frame_4)
        self.lbbilgi2.setGeometry(QtCore.QRect(150, 30, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbbilgi2.setFont(font)
        self.lbbilgi2.setText("")
        self.lbbilgi2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbbilgi2.setObjectName("lbbilgi2")
        self.gbbilgi = QtWidgets.QGroupBox(self.sfbilgi)
        self.gbbilgi.setGeometry(QtCore.QRect(340, 100, 771, 731))
        self.gbbilgi.setStyleSheet("#gbbilgi{\n"
"  background-color: white;\n"
"    border: 2px solid #333;\n"
"    padding: 20px;\n"
"}")
        self.gbbilgi.setTitle("")
        self.gbbilgi.setObjectName("gbbilgi")
        self.label_3 = QtWidgets.QLabel(self.gbbilgi)
        self.label_3.setGeometry(QtCore.QRect(40, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.gbbilgi)
        self.line.setGeometry(QtCore.QRect(10, 80, 741, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget = QtWidgets.QWidget(self.gbbilgi)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 220, 491, 240))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lnad = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lnad.setFont(font)
        self.lnad.setReadOnly(False)
        self.lnad.setObjectName("lnad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lnad)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lnsoyad = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lnsoyad.setFont(font)
        self.lnsoyad.setReadOnly(False)
        self.lnsoyad.setObjectName("lnsoyad")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lnsoyad)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lnid = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lnid.setFont(font)
        self.lnid.setReadOnly(True)
        self.lnid.setObjectName("lnid")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lnid)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lnbolum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lnbolum.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lnbolum.setFont(font)
        self.lnbolum.setReadOnly(True)
        self.lnbolum.setObjectName("lnbolum")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lnbolum)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lnsifre = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lnsifre.setFont(font)
        self.lnsifre.setReadOnly(False)
        self.lnsifre.setObjectName("lnsifre")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lnsifre)
        self.btnguncelle = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnguncelle.setStyleSheet("#btnguncelle {\n"
"    background-color: #3498db;     \n"
"    color: white;                 \n"
"    border: 2px solid #2980b9;     \n"
"    border-radius: 8px;           \n"
"    padding: 6px 12px;           \n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#btnguncelle:hover {\n"
"    background-color: #2980b9;     \n"
"}\n"
"\n"
"#btnguncelle:pressed {\n"
"    background-color: #2471a3;     \n"
"}")
        self.btnguncelle.setObjectName("btnguncelle")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnguncelle)
        self.stackedWidget.addWidget(self.sfbilgi)
        self.sfnot = QtWidgets.QWidget()
        self.sfnot.setObjectName("sfnot")
        self.frame_5 = QtWidgets.QFrame(self.sfnot)
        self.frame_5.setGeometry(QtCore.QRect(0, 20, 331, 841))
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 301, 721))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnkapa3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnkapa3.setFont(font)
        self.btnkapa3.setStyleSheet("#btnkapa3{\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#btnkapa3:hover {\n"
"    background-color: darkred;\n"
"}\n"
"\n"
"#btnkapa3:pressed {\n"
"    background-color: #990000;\n"
"}")
        self.btnkapa3.setObjectName("btnkapa3")
        self.verticalLayout_4.addWidget(self.btnkapa3)
        self.btncikis3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btncikis3.setStyleSheet("#btncikis3 {\n"
"    background-color: #2ecc71;   \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"#btncikis3:hover {\n"
"    background-color: #27ae60;  \n"
"}\n"
"#btncikis3:pressed{\n"
"background-color: #1e8449;\n"
"}\n"
"")
        self.btncikis3.setObjectName("btncikis3")
        self.verticalLayout_4.addWidget(self.btncikis3)
        self.btnana3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnana3.setFont(font)
        self.btnana3.setStyleSheet("#btnana3 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnana3:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnana3.setObjectName("btnana3")
        self.verticalLayout_4.addWidget(self.btnana3)
        self.btnobilgi3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnobilgi3.setFont(font)
        self.btnobilgi3.setStyleSheet("#btnobilgi3 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnobilgi3:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnobilgi3.setObjectName("btnobilgi3")
        self.verticalLayout_4.addWidget(self.btnobilgi3)
        self.btnnotbilgi3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnnotbilgi3.setFont(font)
        self.btnnotbilgi3.setStyleSheet("#btnnotbilgi3 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnnotbilgi3:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnnotbilgi3.setObjectName("btnnotbilgi3")
        self.verticalLayout_4.addWidget(self.btnnotbilgi3)
        self.btnsinif3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnsinif3.setFont(font)
        self.btnsinif3.setStyleSheet("#btnsinif3 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnsinif3:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnsinif3.setObjectName("btnsinif3")
        self.verticalLayout_4.addWidget(self.btnsinif3)
        self.frame_6 = QtWidgets.QFrame(self.sfnot)
        self.frame_6.setGeometry(QtCore.QRect(330, 10, 801, 80))
        self.frame_6.setStyleSheet("#frame_6{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lbbilgi3 = QtWidgets.QLabel(self.frame_6)
        self.lbbilgi3.setGeometry(QtCore.QRect(150, 30, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbbilgi3.setFont(font)
        self.lbbilgi3.setText("")
        self.lbbilgi3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbbilgi3.setObjectName("lbbilgi3")
        self.gbnot = QtWidgets.QGroupBox(self.sfnot)
        self.gbnot.setGeometry(QtCore.QRect(340, 100, 771, 731))
        self.gbnot.setStyleSheet("#gbnot{\n"
"  background-color: white;\n"
"    border: 2px solid #333;\n"
"    padding: 20px;\n"
"}")
        self.gbnot.setTitle("")
        self.gbnot.setObjectName("gbnot")
        self.label_8 = QtWidgets.QLabel(self.gbnot)
        self.label_8.setGeometry(QtCore.QRect(40, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_2 = QtWidgets.QFrame(self.gbnot)
        self.line_2.setGeometry(QtCore.QRect(10, 80, 741, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_11 = QtWidgets.QLabel(self.gbnot)
        self.label_11.setGeometry(QtCore.QRect(50, 240, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.gbnot)
        self.label_12.setGeometry(QtCore.QRect(230, 240, 481, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.line_4 = QtWidgets.QFrame(self.gbnot)
        self.line_4.setGeometry(QtCore.QRect(50, 260, 171, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.gbnot)
        self.line_5.setGeometry(QtCore.QRect(240, 260, 461, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_20 = QtWidgets.QLabel(self.gbnot)
        self.label_20.setGeometry(QtCore.QRect(50, 470, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lblort = QtWidgets.QLabel(self.gbnot)
        self.lblort.setGeometry(QtCore.QRect(260, 470, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblort.setFont(font)
        self.lblort.setText("")
        self.lblort.setObjectName("lblort")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.gbnot)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(49, 290, 171, 151))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lnders1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnders1.setFont(font)
        self.lnders1.setReadOnly(True)
        self.lnders1.setObjectName("lnders1")
        self.verticalLayout_9.addWidget(self.lnders1)
        self.lnders2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnders2.setFont(font)
        self.lnders2.setReadOnly(True)
        self.lnders2.setObjectName("lnders2")
        self.verticalLayout_9.addWidget(self.lnders2)
        self.lnders3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnders3.setFont(font)
        self.lnders3.setReadOnly(True)
        self.lnders3.setObjectName("lnders3")
        self.verticalLayout_9.addWidget(self.lnders3)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.gbnot)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(250, 290, 191, 151))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lnvizenot = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnvizenot.setFont(font)
        self.lnvizenot.setReadOnly(True)
        self.lnvizenot.setObjectName("lnvizenot")
        self.verticalLayout_10.addWidget(self.lnvizenot)
        self.lnvizenot2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnvizenot2.setFont(font)
        self.lnvizenot2.setReadOnly(True)
        self.lnvizenot2.setObjectName("lnvizenot2")
        self.verticalLayout_10.addWidget(self.lnvizenot2)
        self.lnvizenot3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnvizenot3.setFont(font)
        self.lnvizenot3.setReadOnly(True)
        self.lnvizenot3.setObjectName("lnvizenot3")
        self.verticalLayout_10.addWidget(self.lnvizenot3)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.gbnot)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(480, 290, 201, 151))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lnfinalnot = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnfinalnot.setFont(font)
        self.lnfinalnot.setReadOnly(True)
        self.lnfinalnot.setObjectName("lnfinalnot")
        self.verticalLayout_11.addWidget(self.lnfinalnot)
        self.lnfinalnot2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnfinalnot2.setFont(font)
        self.lnfinalnot2.setReadOnly(True)
        self.lnfinalnot2.setObjectName("lnfinalnot2")
        self.verticalLayout_11.addWidget(self.lnfinalnot2)
        self.lnfinalnot3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnfinalnot3.setFont(font)
        self.lnfinalnot3.setReadOnly(True)
        self.lnfinalnot3.setObjectName("lnfinalnot3")
        self.verticalLayout_11.addWidget(self.lnfinalnot3)
        self.stackedWidget.addWidget(self.sfnot)
        self.sfsinif = QtWidgets.QWidget()
        self.sfsinif.setObjectName("sfsinif")
        self.frame_7 = QtWidgets.QFrame(self.sfsinif)
        self.frame_7.setGeometry(QtCore.QRect(0, 20, 331, 841))
        self.frame_7.setStyleSheet("#frame_7{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 301, 721))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnkapa4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnkapa4.setFont(font)
        self.btnkapa4.setStyleSheet("#btnkapa4 {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#btnkapa4:hover {\n"
"    background-color: darkred;\n"
"}\n"
"\n"
"#btnkapa4:pressed {\n"
"    background-color: #990000;\n"
"}")
        self.btnkapa4.setObjectName("btnkapa4")
        self.verticalLayout_5.addWidget(self.btnkapa4)
        self.btncikis4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btncikis4.setStyleSheet("#btncikis4 {\n"
"    background-color: #2ecc71;   \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"#btncikis4:hover {\n"
"    background-color: #27ae60;  \n"
"}\n"
"#btncikis4:pressed{\n"
"background-color: #1e8449;\n"
"}\n"
"")
        self.btncikis4.setObjectName("btncikis4")
        self.verticalLayout_5.addWidget(self.btncikis4)
        self.btnana4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnana4.setFont(font)
        self.btnana4.setStyleSheet("#btnana4 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnana4:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnana4.setObjectName("btnana4")
        self.verticalLayout_5.addWidget(self.btnana4)
        self.btnobilgi4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnobilgi4.setFont(font)
        self.btnobilgi4.setStyleSheet("#btnobilgi4 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnobilgi4:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnobilgi4.setObjectName("btnobilgi4")
        self.verticalLayout_5.addWidget(self.btnobilgi4)
        self.btnnotbilgi4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnnotbilgi4.setFont(font)
        self.btnnotbilgi4.setStyleSheet("#btnnotbilgi4 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnnotbilgi4:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnnotbilgi4.setObjectName("btnnotbilgi4")
        self.verticalLayout_5.addWidget(self.btnnotbilgi4)
        self.btnsinif4 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnsinif4.setFont(font)
        self.btnsinif4.setStyleSheet("#btnsinif4 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnsinif4:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnsinif4.setObjectName("btnsinif4")
        self.verticalLayout_5.addWidget(self.btnsinif4)
        self.frame_8 = QtWidgets.QFrame(self.sfsinif)
        self.frame_8.setGeometry(QtCore.QRect(330, 10, 801, 80))
        self.frame_8.setStyleSheet("#frame_8{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.lbbilgi4 = QtWidgets.QLabel(self.frame_8)
        self.lbbilgi4.setGeometry(QtCore.QRect(150, 30, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbbilgi4.setFont(font)
        self.lbbilgi4.setText("")
        self.lbbilgi4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbbilgi4.setObjectName("lbbilgi4")
        self.gbsinif = QtWidgets.QGroupBox(self.sfsinif)
        self.gbsinif.setGeometry(QtCore.QRect(340, 100, 771, 731))
        self.gbsinif.setStyleSheet("#gbsinif{\n"
"  background-color: white;\n"
"    border: 2px solid #333;\n"
"    padding: 20px;\n"
"}")
        self.gbsinif.setTitle("")
        self.gbsinif.setObjectName("gbsinif")
        self.label_9 = QtWidgets.QLabel(self.gbsinif)
        self.label_9.setGeometry(QtCore.QRect(40, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_3 = QtWidgets.QFrame(self.gbsinif)
        self.line_3.setGeometry(QtCore.QRect(10, 80, 741, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tablesinif = QtWidgets.QTableWidget(self.gbsinif)
        self.tablesinif.setGeometry(QtCore.QRect(30, 200, 711, 351))
        self.tablesinif.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tablesinif.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablesinif.setObjectName("tablesinif")
        self.tablesinif.setColumnCount(3)
        self.tablesinif.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablesinif.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesinif.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablesinif.setHorizontalHeaderItem(2, item)
        self.lbsinif = QtWidgets.QLabel(self.gbsinif)
        self.lbsinif.setGeometry(QtCore.QRect(40, 150, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbsinif.setFont(font)
        self.lbsinif.setText("")
        self.lbsinif.setObjectName("lbsinif")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gbsinif)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 570, 121, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.lblmevcut = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblmevcut.setText("")
        self.lblmevcut.setAlignment(QtCore.Qt.AlignCenter)
        self.lblmevcut.setObjectName("lblmevcut")
        self.horizontalLayout.addWidget(self.lblmevcut)
        self.stackedWidget.addWidget(self.sfsinif)
        self.sfogretmen = QtWidgets.QWidget()
        self.sfogretmen.setObjectName("sfogretmen")
        self.frame_9 = QtWidgets.QFrame(self.sfogretmen)
        self.frame_9.setGeometry(QtCore.QRect(0, 20, 331, 841))
        self.frame_9.setStyleSheet("#frame_9{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame_9)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 301, 721))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnkapa5 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnkapa5.setFont(font)
        self.btnkapa5.setStyleSheet("#btnkapa5 {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#btnkapa5:hover {\n"
"    background-color: darkred;\n"
"}\n"
"\n"
"#btnkapa5:pressed {\n"
"    background-color: #990000;\n"
"}")
        self.btnkapa5.setObjectName("btnkapa5")
        self.verticalLayout_7.addWidget(self.btnkapa5)
        self.btncikis5 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.btncikis5.setStyleSheet("#btncikis5 {\n"
"    background-color: #2ecc71;   \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"#btncikis5:hover {\n"
"    background-color: #27ae60;  \n"
"}\n"
"#btncikis5:pressed{\n"
"background-color: #1e8449;\n"
"}\n"
"")
        self.btncikis5.setObjectName("btncikis5")
        self.verticalLayout_7.addWidget(self.btncikis5)
        self.btnana5 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnana5.setFont(font)
        self.btnana5.setStyleSheet("#btnana5 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnana5:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnana5.setObjectName("btnana5")
        self.verticalLayout_7.addWidget(self.btnana5)
        self.btnduzen = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnduzen.setFont(font)
        self.btnduzen.setStyleSheet("#btnduzen {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnduzen:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnduzen.setObjectName("btnduzen")
        self.verticalLayout_7.addWidget(self.btnduzen)
        self.frame_10 = QtWidgets.QFrame(self.sfogretmen)
        self.frame_10.setGeometry(QtCore.QRect(330, 10, 801, 80))
        self.frame_10.setStyleSheet("#frame_10{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.lbbilgi5 = QtWidgets.QLabel(self.frame_10)
        self.lbbilgi5.setGeometry(QtCore.QRect(150, 30, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbbilgi5.setFont(font)
        self.lbbilgi5.setText("")
        self.lbbilgi5.setAlignment(QtCore.Qt.AlignCenter)
        self.lbbilgi5.setObjectName("lbbilgi5")
        self.gbsinif_2 = QtWidgets.QGroupBox(self.sfogretmen)
        self.gbsinif_2.setGeometry(QtCore.QRect(340, 100, 771, 731))
        self.gbsinif_2.setStyleSheet("#gbsinif_2{\n"
"  background-color: white;\n"
"    border: 2px solid #333;\n"
"    padding: 20px;\n"
"}")
        self.gbsinif_2.setTitle("")
        self.gbsinif_2.setObjectName("gbsinif_2")
        self.lbsinif_2 = QtWidgets.QLabel(self.gbsinif_2)
        self.lbsinif_2.setGeometry(QtCore.QRect(40, 150, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbsinif_2.setFont(font)
        self.lbsinif_2.setText("")
        self.lbsinif_2.setObjectName("lbsinif_2")
        self.label_13 = QtWidgets.QLabel(self.gbsinif_2)
        self.label_13.setGeometry(QtCore.QRect(30, 120, 701, 291))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.sfogretmen)
        self.sfduzen = QtWidgets.QWidget()
        self.sfduzen.setObjectName("sfduzen")
        self.frame_11 = QtWidgets.QFrame(self.sfduzen)
        self.frame_11.setGeometry(QtCore.QRect(0, 20, 331, 841))
        self.frame_11.setStyleSheet("#frame_11{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.frame_11)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(20, 10, 301, 721))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnkapa6 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnkapa6.setFont(font)
        self.btnkapa6.setStyleSheet("#btnkapa6 {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"#btnkapa6:hover {\n"
"    background-color: darkred;\n"
"}\n"
"\n"
"#btnkapa6:pressed {\n"
"    background-color: #990000;\n"
"}")
        self.btnkapa6.setObjectName("btnkapa6")
        self.verticalLayout_8.addWidget(self.btnkapa6)
        self.btncikis6 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.btncikis6.setStyleSheet("#btncikis6 {\n"
"    background-color: #2ecc71;   \n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"#btncikis6:hover {\n"
"    background-color: #27ae60;  \n"
"}\n"
"#btncikis6:pressed{\n"
"background-color: #1e8449;\n"
"}\n"
"")
        self.btncikis6.setObjectName("btncikis6")
        self.verticalLayout_8.addWidget(self.btncikis6)
        self.btnana6 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnana6.setFont(font)
        self.btnana6.setStyleSheet("#btnana6 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnana6:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnana6.setObjectName("btnana6")
        self.verticalLayout_8.addWidget(self.btnana6)
        self.btnduzen2 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnduzen2.setFont(font)
        self.btnduzen2.setStyleSheet("#btnduzen2 {\n"
"    background-color: #d6eaff;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"#btnduzen2:hover {\n"
"    background-color: #c0ddff; \n"
"}")
        self.btnduzen2.setObjectName("btnduzen2")
        self.verticalLayout_8.addWidget(self.btnduzen2)
        self.frame_12 = QtWidgets.QFrame(self.sfduzen)
        self.frame_12.setGeometry(QtCore.QRect(330, 10, 801, 80))
        self.frame_12.setStyleSheet("#frame_12{\n"
"background-color: #d6eaff;\n"
"    border: 2px solid black;\n"
"\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.lbbilgi6 = QtWidgets.QLabel(self.frame_12)
        self.lbbilgi6.setGeometry(QtCore.QRect(150, 30, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbbilgi6.setFont(font)
        self.lbbilgi6.setText("")
        self.lbbilgi6.setAlignment(QtCore.Qt.AlignCenter)
        self.lbbilgi6.setObjectName("lbbilgi6")
        self.gbsinif_3 = QtWidgets.QGroupBox(self.sfduzen)
        self.gbsinif_3.setGeometry(QtCore.QRect(340, 100, 771, 731))
        self.gbsinif_3.setStyleSheet("#gbsinif_3{\n"
"  background-color: white;\n"
"    border: 2px solid #333;\n"
"    padding: 20px;\n"
"}")
        self.gbsinif_3.setTitle("")
        self.gbsinif_3.setObjectName("gbsinif_3")
        self.label_14 = QtWidgets.QLabel(self.gbsinif_3)
        self.label_14.setGeometry(QtCore.QRect(40, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line_6 = QtWidgets.QFrame(self.gbsinif_3)
        self.line_6.setGeometry(QtCore.QRect(10, 80, 741, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.tableogretmen = QtWidgets.QTableWidget(self.gbsinif_3)
        self.tableogretmen.setGeometry(QtCore.QRect(10, 100, 751, 291))
        self.tableogretmen.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableogretmen.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableogretmen.setObjectName("tableogretmen")
        self.tableogretmen.setColumnCount(11)
        self.tableogretmen.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableogretmen.setHorizontalHeaderItem(10, item)
        self.groupBox = QtWidgets.QGroupBox(self.gbsinif_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 400, 751, 171))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 361, 165))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lnidgoster = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnidgoster.setFont(font)
        self.lnidgoster.setObjectName("lnidgoster")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lnidgoster)
        self.lnadgoster = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnadgoster.setFont(font)
        self.lnadgoster.setObjectName("lnadgoster")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lnadgoster)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lnsoyadgoster = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnsoyadgoster.setFont(font)
        self.lnsoyadgoster.setObjectName("lnsoyadgoster")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lnsoyadgoster)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lnsifregoster = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnsifregoster.setFont(font)
        self.lnsifregoster.setObjectName("lnsifregoster")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lnsifregoster)
        self.cbbolumgoster = QtWidgets.QComboBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbbolumgoster.setFont(font)
        self.cbbolumgoster.setObjectName("cbbolumgoster")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbbolumgoster)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(380, 10, 181, 141))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lnvizegoster1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnvizegoster1.setFont(font)
        self.lnvizegoster1.setObjectName("lnvizegoster1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lnvizegoster1)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lnvizegoster2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnvizegoster2.setFont(font)
        self.lnvizegoster2.setObjectName("lnvizegoster2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lnvizegoster2)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lnvizegoster3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnvizegoster3.setFont(font)
        self.lnvizegoster3.setObjectName("lnvizegoster3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lnvizegoster3)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(560, 10, 182, 141))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lnfinalgoster1 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnfinalgoster1.setFont(font)
        self.lnfinalgoster1.setObjectName("lnfinalgoster1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lnfinalgoster1)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lnfinalgoster2 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnfinalgoster2.setFont(font)
        self.lnfinalgoster2.setObjectName("lnfinalgoster2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lnfinalgoster2)
        self.lnfinalgoster3 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lnfinalgoster3.setFont(font)
        self.lnfinalgoster3.setObjectName("lnfinalgoster3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lnfinalgoster3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gbsinif_3)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 580, 361, 141))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnekle = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnekle.setStyleSheet("#btnekle{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btnekle:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btnekle.setObjectName("btnekle")
        self.gridLayout_2.addWidget(self.btnekle, 0, 0, 1, 1)
        self.btnsil = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnsil.setStyleSheet("#btnsil{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btnsil:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btnsil.setObjectName("btnsil")
        self.gridLayout_2.addWidget(self.btnsil, 0, 1, 1, 1)
        self.btnyeni = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnyeni.setStyleSheet("#btnyeni{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btnyeni:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btnyeni.setObjectName("btnyeni")
        self.gridLayout_2.addWidget(self.btnyeni, 1, 0, 1, 1)
        self.btnduzelt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnduzelt.setStyleSheet("#btnduzelt{\n"
"    background-color: #eeeeee;\n"
"    border: 1px solid #333;\n"
"    padding: 5px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"#btnduzelt:hover {\n"
"    background-color: #dddddd;\n"
"}")
        self.btnduzelt.setObjectName("btnduzelt")
        self.gridLayout_2.addWidget(self.btnduzelt, 1, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gbsinif_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(360, 39, 301, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.label_28)
        self.lnara = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lnara.setFont(font)
        self.lnara.setObjectName("lnara")
        self.horizontalLayout_2.addWidget(self.lnara)
        self.stackedWidget.addWidget(self.sfduzen)

        self.retranslateUi(OBS)
        QtCore.QMetaObject.connectSlotsByName(OBS)

    def retranslateUi(self, OBS):
        _translate = QtCore.QCoreApplication.translate
        OBS.setWindowTitle(_translate("OBS", "OBS"))
        self.lngirisid.setInputMask(_translate("OBS", "999"))
        self.lngirisid.setPlaceholderText(_translate("OBS", "Öğrenci Id"))
        self.lngirissifre.setPlaceholderText(_translate("OBS", "Öğrenci Şifre"))
        self.label.setText(_translate("OBS", "Hoşgeldiniz! Aşağıdan sisteme giriş yapınız."))
        self.btngiris.setToolTip(_translate("OBS", "Sisteme giriş yapın."))
        self.btngiris.setText(_translate("OBS", "Giriş"))
        self.btngiriskayit.setToolTip(_translate("OBS", "Hesabınız yok mu? Hemen kayıt olun!"))
        self.btngiriskayit.setText(_translate("OBS", "Kayıt ol"))
        self.btngiriscikis.setToolTip(_translate("OBS", "Sistemi kapatmak için tıklayınız."))
        self.btngiriscikis.setText(_translate("OBS", "Çıkış"))
        self.lnkayitid.setInputMask(_translate("OBS", "999"))
        self.lnkayitid.setPlaceholderText(_translate("OBS", "Öğrenci Id"))
        self.lnkayitad.setPlaceholderText(_translate("OBS", "Öğrenci Ad"))
        self.lnkayitsoyad.setPlaceholderText(_translate("OBS", "Öğrenci Soyad"))
        self.lnkayitsifretekrar.setPlaceholderText(_translate("OBS", "Öğrenci Şifre Tekrar"))
        self.lnkayitsifre.setPlaceholderText(_translate("OBS", "Öğrenci Şifre"))
        self.cbbolum.setToolTip(_translate("OBS", "Bölümler"))
        self.btnkayit.setToolTip(_translate("OBS", "Hesabınız yok mu? Hemen kayıt olun!"))
        self.btnkayit.setText(_translate("OBS", "Kayıt ol"))
        self.btngirisdon.setText(_translate("OBS", "Girişe Dön"))
        self.btnkayitcikis.setToolTip(_translate("OBS", "Sistemi kapatmak için tıklayınız."))
        self.btnkayitcikis.setText(_translate("OBS", "Çıkış"))
        self.btnkapa.setToolTip(_translate("OBS", "Sistemi kapatmak için tıklayınız."))
        self.btnkapa.setText(_translate("OBS", "Çıkış"))
        self.btncikis.setToolTip(_translate("OBS", "Oturumu kapatmak için tıklayınız."))
        self.btncikis.setText(_translate("OBS", "Oturumu Kapat"))
        self.btnana.setToolTip(_translate("OBS", "Ana sayfayı görmek için tıklayınız."))
        self.btnana.setText(_translate("OBS", "Ana Sayfa"))
        self.btnobilgi.setToolTip(_translate("OBS", "Öğrenci bilgilerini görmek için tıklayınız."))
        self.btnobilgi.setText(_translate("OBS", "Öğrenci Bilgileri"))
        self.btnnotbilgi.setToolTip(_translate("OBS", "Not bilgilerini girmek için tıklayınız."))
        self.btnnotbilgi.setText(_translate("OBS", "Not Bilgileri"))
        self.btnsinif.setText(_translate("OBS", "Sınıf Bilgileri"))
        self.label_2.setText(_translate("OBS", "Hoş geldiniz!\n"
"\n"
"Bu uygulama üzerinden:\n"
"- Notlarınızı görüntüleyebilir,\n"
"- Öğrenci bilgilerinize erişebilir,\n"
"- Sınıfınızdaki öğrencileri görüntüleyebilir,\n"
"- Ortalama hesaplamalarını görebilirsiniz."))
        self.btnkapa2.setToolTip(_translate("OBS", "Sistemi kapatmak için tıklayınız."))
        self.btnkapa2.setText(_translate("OBS", "Çıkış"))
        self.btncikis2.setToolTip(_translate("OBS", "Oturumu kapatmak için tıklayınız."))
        self.btncikis2.setText(_translate("OBS", "Oturumu Kapat"))
        self.btnana2.setToolTip(_translate("OBS", "Ana sayfayı görmek için tıklayınız."))
        self.btnana2.setText(_translate("OBS", "Ana Sayfa"))
        self.btnobilgi2.setToolTip(_translate("OBS", "Öğrenci bilgilerini görmek için tıklayınız."))
        self.btnobilgi2.setText(_translate("OBS", "Öğrenci Bilgileri"))
        self.btnnotbilgi2.setToolTip(_translate("OBS", "Not bilgilerini girmek için tıklayınız."))
        self.btnnotbilgi2.setText(_translate("OBS", "Not Bilgileri"))
        self.btnsinif2.setText(_translate("OBS", "Sınıf Bilgileri"))
        self.label_3.setText(_translate("OBS", "Öğrenci Bilgileri"))
        self.label_4.setText(_translate("OBS", "Ad:"))
        self.label_5.setText(_translate("OBS", "Soyad:"))
        self.label_6.setText(_translate("OBS", "ID:"))
        self.label_7.setText(_translate("OBS", "Bölüm:"))
        self.label_10.setText(_translate("OBS", "Şifre:"))
        self.btnguncelle.setText(_translate("OBS", "Bilgileri Güncelle"))
        self.btnkapa3.setToolTip(_translate("OBS", "Sistemi kapatmak için tıklayınız."))
        self.btnkapa3.setText(_translate("OBS", "Çıkış"))
        self.btncikis3.setToolTip(_translate("OBS", "Oturumu kapatmak için tıklayınız."))
        self.btncikis3.setText(_translate("OBS", "Oturumu Kapat"))
        self.btnana3.setToolTip(_translate("OBS", "Ana sayfayı görmek için tıklayınız."))
        self.btnana3.setText(_translate("OBS", "Ana Sayfa"))
        self.btnobilgi3.setToolTip(_translate("OBS", "Öğrenci bilgilerini görmek için tıklayınız."))
        self.btnobilgi3.setText(_translate("OBS", "Öğrenci Bilgileri"))
        self.btnnotbilgi3.setToolTip(_translate("OBS", "Not bilgilerini girmek için tıklayınız."))
        self.btnnotbilgi3.setText(_translate("OBS", "Not Bilgileri"))
        self.btnsinif3.setText(_translate("OBS", "Sınıf Bilgileri"))
        self.label_8.setText(_translate("OBS", "Not Bilgileri"))
        self.label_11.setText(_translate("OBS", "Dersler"))
        self.label_12.setText(_translate("OBS", "Notlar"))
        self.label_20.setText(_translate("OBS", "Öğrencinin Ortalaması:"))
        self.btnkapa4.setToolTip(_translate("OBS", "Sistemi kapatmak için tıklayınız."))
        self.btnkapa4.setText(_translate("OBS", "Çıkış"))
        self.btncikis4.setToolTip(_translate("OBS", "Oturumu kapatmak için tıklayınız."))
        self.btncikis4.setText(_translate("OBS", "Oturumu Kapat"))
        self.btnana4.setToolTip(_translate("OBS", "Ana sayfayı görmek için tıklayınız."))
        self.btnana4.setText(_translate("OBS", "Ana Sayfa"))
        self.btnobilgi4.setToolTip(_translate("OBS", "Öğrenci bilgilerini görmek için tıklayınız."))
        self.btnobilgi4.setText(_translate("OBS", "Öğrenci Bilgileri"))
        self.btnnotbilgi4.setToolTip(_translate("OBS", "Not bilgilerini girmek için tıklayınız."))
        self.btnnotbilgi4.setText(_translate("OBS", "Not Bilgileri"))
        self.btnsinif4.setText(_translate("OBS", "Sınıf Bilgileri"))
        self.label_9.setText(_translate("OBS", "Sınıf Bilgileri"))
        item = self.tablesinif.horizontalHeaderItem(0)
        item.setText(_translate("OBS", "Öğrenci ID"))
        item = self.tablesinif.horizontalHeaderItem(1)
        item.setText(_translate("OBS", "Ad"))
        item = self.tablesinif.horizontalHeaderItem(2)
        item.setText(_translate("OBS", "Soyad"))
        self.label_19.setText(_translate("OBS", "Sınıf Mevcudu:"))
        self.btnkapa5.setText(_translate("OBS", "Çıkış"))
        self.btncikis5.setText(_translate("OBS", "Oturumu Kapat"))
        self.btnana5.setToolTip(_translate("OBS", "Ana sayfayı görmek için tıklayınız."))
        self.btnana5.setText(_translate("OBS", "Ana Sayfa"))
        self.btnduzen.setToolTip(_translate("OBS", "Öğrenci bilgilerini görmek için tıklayınız."))
        self.btnduzen.setText(_translate("OBS", "Düzenleme"))
        self.label_13.setText(_translate("OBS", "Hoş geldiniz!\n"
"Yönetici girişi yaptınız.\n"
"\n"
"Bu uygulama üzerinden öğrencileri görüntüleyip\n"
"öğrencilerle alakalı işlemler yapabilirsiniz."))
        self.btnkapa6.setText(_translate("OBS", "Çıkış"))
        self.btncikis6.setText(_translate("OBS", "Oturumu Kapat"))
        self.btnana6.setToolTip(_translate("OBS", "Ana sayfayı görmek için tıklayınız."))
        self.btnana6.setText(_translate("OBS", "Ana Sayfa"))
        self.btnduzen2.setToolTip(_translate("OBS", "Öğrenci bilgilerini görmek için tıklayınız."))
        self.btnduzen2.setText(_translate("OBS", "Düzenleme"))
        self.label_14.setText(_translate("OBS", "Düzenleme"))
        item = self.tableogretmen.horizontalHeaderItem(0)
        item.setText(_translate("OBS", "ID"))
        item = self.tableogretmen.horizontalHeaderItem(1)
        item.setText(_translate("OBS", "Ad"))
        item = self.tableogretmen.horizontalHeaderItem(2)
        item.setText(_translate("OBS", "Soyad"))
        item = self.tableogretmen.horizontalHeaderItem(3)
        item.setText(_translate("OBS", "Bölüm"))
        item = self.tableogretmen.horizontalHeaderItem(4)
        item.setText(_translate("OBS", "Şifre"))
        item = self.tableogretmen.horizontalHeaderItem(5)
        item.setText(_translate("OBS", "1. Vize Notu"))
        item = self.tableogretmen.horizontalHeaderItem(6)
        item.setText(_translate("OBS", "2. Vize Notu"))
        item = self.tableogretmen.horizontalHeaderItem(7)
        item.setText(_translate("OBS", "3. Vize Notu"))
        item = self.tableogretmen.horizontalHeaderItem(8)
        item.setText(_translate("OBS", "1. Final Notu"))
        item = self.tableogretmen.horizontalHeaderItem(9)
        item.setText(_translate("OBS", "2. Final Notu"))
        item = self.tableogretmen.horizontalHeaderItem(10)
        item.setText(_translate("OBS", "3. Final Notu"))
        self.label_15.setText(_translate("OBS", "ID:"))
        self.lnidgoster.setInputMask(_translate("OBS", "999"))
        self.label_16.setText(_translate("OBS", "Ad:"))
        self.label_17.setText(_translate("OBS", "Soyad:"))
        self.label_18.setText(_translate("OBS", "Bölüm:"))
        self.label_27.setText(_translate("OBS", "Şifre:"))
        self.lnvizegoster1.setInputMask(_translate("OBS", "999"))
        self.label_22.setText(_translate("OBS", "2. Vize Notu:"))
        self.lnvizegoster2.setInputMask(_translate("OBS", "999"))
        self.label_23.setText(_translate("OBS", "3. Vize Notu:"))
        self.lnvizegoster3.setInputMask(_translate("OBS", "999"))
        self.label_21.setText(_translate("OBS", "1. Vize Notu:"))
        self.label_24.setText(_translate("OBS", "1. Final Notu:"))
        self.lnfinalgoster1.setInputMask(_translate("OBS", "999"))
        self.label_25.setText(_translate("OBS", "2. Final Notu:"))
        self.label_26.setText(_translate("OBS", "3. Final Notu:"))
        self.lnfinalgoster2.setInputMask(_translate("OBS", "999"))
        self.lnfinalgoster3.setInputMask(_translate("OBS", "999"))
        self.btnekle.setText(_translate("OBS", "Ekle"))
        self.btnsil.setText(_translate("OBS", "Sil"))
        self.btnyeni.setText(_translate("OBS", "Yeni"))
        self.btnduzelt.setText(_translate("OBS", "Güncelle"))
        self.label_28.setText(_translate("OBS", "Ara:"))
